# Generated by Django 4.2.17 on 2025-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('authors', models.TextField()),
                ('publication_date', models.DateField(blank=True)),
                ('conf_or_journal_name', models.CharField(max_length=220)),
                ('publisher', models.CharField(max_length=100)),
                ('is_journal', models.CharField(choices=[(0, 'No'), (1, 'Yes')], default=1, max_length=2)),
                ('abstract', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
