# Generated by Django 4.2.17 on 2025-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_journal',
            field=models.CharField(choices=[(0, 'No'), (1, 'Yes')], default='Please select..', max_length=2),
        ),
    ]
