# Generated by Django 4.2.17 on 2025-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publication_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_year',
            field=models.DateField(blank=True),
        ),
    ]
