# Generated by Django 4.2.17 on 2025-01-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_journal',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
    ]
