# Generated by Django 4.2.17 on 2025-01-14 22:12

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=155)),
                ('employer_name', models.CharField(max_length=100)),
                ('office_name', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('current_city', models.CharField(max_length=50)),
                ('phone_no', phone_field.models.PhoneField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('profile_image', models.FileField(blank=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
