# Generated by Django 4.2.17 on 2025-01-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
