# Generated by Django 4.2.17 on 2025-01-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='job_title',
        ),
    ]
